<?php

namespace App\Command;

use App\Entity\Medicijnen;
use Doctrine\ORM\EntityManagerInterface;
use Faker\Factory;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(
  name: 'app:seed-medicines',
  description: 'Seeds 1000 medicines (Generic & Brand) without purging the database',
)]
class SeedMedicijnenCommand extends Command
{
  public function __construct(
    private EntityManagerInterface $em
  ) {
    parent::__construct();
  }

  protected function execute(InputInterface $input, OutputInterface $output): int
  {
    $io = new SymfonyStyle($input, $output);

    // Initialize Faker with Dutch locale
    $faker = Factory::create('nl_NL');

    $baseMedicines = [
      'Paracetamol',
      'Ibuprofen',
      'Amoxicilline',
      'Omeprazol',
      'Diclofenac',
      'Metformine',
      'Salbutamol',
      'Atorvastatine',
      'Pantoprazol',
      'Losartan',
      'Simvastatine',
      'Amlodipine',
      'Hydrochloorthiazide',
      'Ramipril',
      'Bisoprolol',
      'Metoprolol',
      'Levothyroxine',
      'Esomeprazol',
      'Rosuvastatine',
      'Furosemide',
      'Naproxen',
      'Codeïne',
      'Tramadol',
      'Prednisolon',
      'Diazepam',
      'Oxazepam',
      'Temazepam',
      'Zolpidem',
      'Citalopram',
      'Sertraline',
      'Fluoxetine',
      'Amitriptyline',
      'Venlafaxine',
      'Mirtazapine',
      'Quetiapine',
      'Risperidon',
      'Olanzapine',
      'Haloperidol',
      'Metoclopramide',
      'Domperidon',
      'Loperamide',
      'Mebeverine',
      'Mesalazine',
      'Azathioprine',
      'Methotrexaat',
      'Allopurinol',
      'Spironolacton',
      'Digoxine',
      'Warfarine',
      'Acenocoumarol',
      'Doxycycline',
      'Claritromycine',
      'Azitromycine',
      'Ciprofloxacine',
      'Nitrofurantoïne',
      'Fluconazol',
      'Terbinafine',
      'Aciclovir',
      'Oseltamivir',
      'Valaciclovir',
      'Metronidazol',
      'Tinidazol',
      'Miconazol',
      'Clotrimazol',
      'Hydrocortison',
      'Betamethason',
      'Triamcinolon',
      'Clobetasol',
      'Fusidinezuur',
      'Mupirocine',
      'Permethrine',
      'Malathion',
      'Rivaroxaban',
      'Apixaban',
      'Dabigatran',
      'Enoxaparine',
      'Heparine',
      'Clopidogrel',
      'Ticagrelor',
      'Prasugrel',
      'Nitroglycerine',
      'Verapamil',
      'Diltiazem',
      'Nifedipine',
      'Felodipine',
      'Barnidipine',
      'Candesartan',
      'Valsartan',
      'Irbesartan',
      'Olmesartan',
      'Telmisartan',
      'Eprosartan',
      'Perindopril',
      'Enalapril',
      'Lisinopril',
      'Captopril',
      'Fosinopril',
      'Quinapril',
      'Tamsulosine',
      'Finasteride',
      'Acarbose',
      'Acetylsalicylzuur',
      'Alprazolam',
      'Amiodaron',
      'Amoxicilline/Clavulaanzuur',
      'Baclofen',
      'Beclometason',
      'Benzylpenicilline',
      'Bezafibraat',
      'Bicalutamide',
      'Budesonide',
      'Bumetanide',
      'Buprenorfine',
      'Buspiron',
      'Cabergoline',
      'Calcitriol',
      'Calciumcarbonaat',
      'Carbamazepine',
      'Carbimazol',
      'Carvedilol',
      'Cefalexine',
      'Ceftriaxon',
      'Celecoxib',
      'Cetirizine',
      'Chlooramfenicol',
      'Chloorhexidine',
      'Chloorpromazine',
      'Chloortalidon',
      'Ciclosporine',
      'Cimetidine',
      'Clarithromycine',
      'Clomipramine',
      'Clonazepam',
      'Clonidine',
      'Clozapine',
      'Colchicine',
      'Desmopressine',
      'Dexamethason',
      'Dextromethorfan',
      'Donepezil',
      'Doxazosine',
      'Duloxetine',
      'Dutasteride',
      'Erytromycine',
      'Escitalopram',
      'Ethinylestradiol',
      'Etoricoxib',
      'Ezetimib',
      'Feneticilline',
      'Fenobarbital',
      'Fenprocoumon',
      'Fentanyl',
      'Ferrofumaraat',
      'Flecaïnide',
      'Flunitrazepam',
      'Fluoride',
      'Fluticasone',
      'Fluvastatine',
      'Fluvoxamine',
      'Folinezuur',
      'Formoterol',
      'Fosfomycine',
      'Gabapentine',
      'Galantamine',
      'Gliclazide',
      'Glimepiride',
      'Glucagon',
      'Glucose',
      'Hydrochinon',
      'Hydromorfon',
      'Hydroxyzine',
      'Hyoscine',
      'Hypromellose',
      'Indapamide',
      'Indometacine',
      'Ipratropium',
      'Isosorbide',
      'Isotretinoïne',
      'Itraconazol',
      'Ketoconazol',
      'Labetalol',
      'Lactulose',
      'Lamotrigine',
      'Lansoprazol',
      'Latanoprost',
      'Leflunomide',
      'Lercanidipine',
      'Letrozol',
      'Levetiracetam',
      'Levocetirizine',
      'Levodopa',
      'Levofloxacine',
      'Lithium',
      'Lormetazepam',
      'Macrogol',
      'Magnesiumhydroxyde',
      'Melatonine',
      'Meloxicam',
      'Memantine',
      'Norethisteron',
      'Nortriptyline',
      'Nystatine',
      'Octreotide',
      'Olopatadine',
      'Olsalazine',
      'Ondansetron',
      'Orlistat',
      'Oxybutynine',
      'Oxycodon',
      'Oxytocine',
      'Paclitaxel',
      'Paliperidon',
      'Pamidronaat',
      'Paroxetine',
      'Pegfilgrastim',
      'Pemetrexed',
      'Penicillamine',
      'Pentoxifylline',
      'Pheneticilline',
      'Fenytoïne',
      'Pilocarpine',
      'Pioglitazon',
      'Piperacilline',
      'Piroxicam',
      'Pizotifeen',
      'Pramipexol',
      'Pravastatine',
      'Prazosine',
      'Pregabaline',
      'Primidon',
      'Probenecide',
      'Procaine',
      'Progesteron',
      'Proguanil',
      'Promethazine',
      'Propofol',
      'Propranolol',
      'Propylthiouracil',
      'Pyrazinamide',
      'Pyridoxine',
      'Raloxifene',
      'Ranitidine',
      'Rasagiline',
      'Remifentanil',
      'Repaglinide',
      'Ribavirine',
      'Rifampicine',
      'Riluzol',
      'Risedronaat',
      'Ritosine',
      'Rituximab',
      'Rivastigmine',
      'Rizatriptan',
      'Ropinirol',
      'Rosiglitazon',
      'Rotigotine',
      'Rufinamide',
      'Salmeterol',
      'Saquinavir',
      'Selegiline',
      'Sevelamer',
      'Sildenafil',
      'Sirolimus',
      'Sitagliptine',
      'Solifenacine',
      'Somatropine',
      'Sotalol',
      'Stavudine',
      'Sucralfaat',
      'Sufentanil',
      'Sulfasalazine',
      'Sulpiride',
      'Sumatriptan',
      'Sunitinib',
      'Tacrolimus',
      'Tadalafil',
      'Tamoxifen',
      'Temozolomide',
      'Tenofovir',
      'Terazosine',
      'Teriparatide',
      'Testosteron',
      'Theofylline',
      'Thiamine',
      'Tiagabine',
      'Tibolon',
      'Ticlopidine',
      'Tilidine',
      'Timolol',
      'Tiotropium',
      'Tizanidine',
      'Tobramycin',
      'Tolbutamide',
      'Tolterodine',
      'Topiramaat',
      'Torasemide',
      'Trandolapril',
      'Tranexaminezuur',
      'Trastuzumab',
      'Travoprost',
      'Trazodon',
      'Tretinoïne',
      'Triamtereen',
      'Triazolam',
      'Trifluoperazine',
      'Trimethoprim',
      'Triptoreline',
      'Valganciclovir',
      'Vancomycine',
      'Vardenafil',
      'Varenicline',
      'Vigabatrine',
      'Vildagliptine',
      'Vinblastine',
      'Vincristine',
      'Vinorelbine',
      'Voriconazol',
      'Xylometazoline',
      'Zidovudine',
      'Zolmitriptan',
      'Zonisamide',
      'Zopiclon',
      'Zuclopentixol',
      'Abacavir',
      'Adalimumab',
      'Alendronaat',
      'Anastrozol',
      'Aripiprazol',
      'Atenolol',
      'Bisfosfonaat',
      'Brimonidine',
      'Capecitabine',
      'Cefotaxim',
      'Etoposide',
      'Exemestaan',
      'Ganciclovir',
      'Gemfibrozil',
      'Gentamicine'
    ];

    $forms = ['Tablet', 'Capsule', 'Drank', 'Zalf', 'Inhalatiepoeder', 'Bruistablet', 'Injectievloeistof'];
    $strengths = ['5 mg', '10 mg', '20 mg', '50 mg', '100 mg', '400 mg', '500 mg', '1000 mg'];

    $io->section('Seeding 1000 Medicines...');
    $io->progressStart(1000);

    for ($i = 0; $i < 1000; $i++) {
      $medicijn = new Medicijnen();

      $name = $baseMedicines[$i % count($baseMedicines)];
      $form = $faker->randomElement($forms);
      $strength = $faker->randomElement($strengths);

      $medicijn->setNaam($name);
      $medicijn->setToedieningsvorm($form);
      $medicijn->setSterkte($strength);
      $medicijn->setBeschrijving($faker->sentence(6));
      $medicijn->setBijsluiter($faker->paragraph(2));

      $this->em->persist($medicijn);

      // Optimization: Flush every 100 records to manage memory
      if (($i % 100) === 0) {
        $this->em->flush();
        $this->em->clear(); // Detach objects to free memory
      }

      $io->progressAdvance();
    }

    $this->em->flush();
    $io->progressFinish();

    $io->success('1000 Medicines seeded successfully!');

    return Command::SUCCESS;
  }
}